### ISSUE TITLE
Possible to include images as base64?

### ISSUE THREAD

**Issue by akrawchyk** [browserify/brfs#67]
Coming from webpack with the ability to use https://github.com/webpack/url-loader to require images as base64, I'm wondering if we can do the same with brfs?

**Comment by mattdesl** [comment]
I just updated [urify](https://www.npmjs.com/package/urify) which aims to provide this feature for browserify.

I also have a plugin which is a bit more like Webpack in that it "emits" files to an output folder if greater than a certain byte threshold. That module needs to be a bit cleaned up, though, for production use. :smile: 

You can also use `fs.readFileSync('foo.png', 'base64')` but it might not be very practical without mime type lookup.
