### ISSUE TITLE
Nested require

### ISSUE THREAD

**Issue by huan086** [browserify/brfs#72]
I'm running with 
    const b = browserify(['./a.js']);
    b.transform(brfs);

File a.js has

```
require('./b.js');
```

File b.js has

```
require('fs').readFileSync(__dirname + 'c.txt');
```

The line in b.js did not get replaced. It seems that brfs only replaces fs in the files specified in browserify sources, but not their dependent files

**Comment by goto-bus-stop** [comment]
This appears to work in recent brfs versions—please open a new issue if you're still seeing this. thanks!
