### ISSUE TITLE
brfs replaces require statement but not readFileSync when path is not required

### ISSUE THREAD

**Issue by Zanibas** [browserify/brfs#74]
So the relevant code is here:

```
const fs = require('fs')
const disclaimer = fs.readFileSync(path.join(__dirname, '..', '..', 'USER_AGREEMENT.md')).toString()
```

In my thoughtlessness, I forgot to include a `require('path')` in my code, but finding this error was troublesome because brfs currently removes the `require` statement, but keeps the `disclaimer` line in the output code.

Thus, errors pop up about `fs` not being defined, but this made it hard to detect that I had forgotten a require statement. 

It would be helpful if an error were thrown when readFileSync lines aren't subbed out. Thank you very much! =)

**Comment by goto-bus-stop** [comment]
This is no longer the case in brfs@2. Thanks!
