### ISSUE TITLE
Remove compromised dependency static-module

### ISSUE THREAD

**Issue by danfinlay** [browserify/brfs#81]
The node-security platform reported that `static-module` is compromised (because it includes `static-eval`), should probably move off it.

**Comment by kujon** [comment]
https://nodesecurity.io/advisories/548 Details of the issue here.

**Comment by george-wilson-iproov** [comment]
This was fixed with https://github.com/browserify/brfs/pull/79 I think - we just need @stevemao to tag a fresh version

**Comment by stevemao** [comment]
I don't think I can publish to npm. If @mattdesl or @substack could add me I'm happy to do it :)

**Comment by kujon** [comment]
Any chance of having this published soon?

**Comment by goto-bus-stop** [comment]
#79 fixed a different issue—fix for this one is in #83.

**Comment by Fjandin** [comment]
Any chance this will be released soon?

**Comment by ljbade** [comment]
Hitting the same problem.

**Comment by ljbade** [comment]
Thanks for fixing this! Now to get upstream modules to update brfs...

**Comment by goto-bus-stop** [comment]
I'm going to release it as a patch once brfs is added to the browserify npm org (probably later today depending on when substack is awake and connected) so upstream modules should automatically get the update :)

**Comment by goto-bus-stop** [comment]
Published as 1.4.4
