### ISSUE TITLE
Read ArrayBuffer for undefined encoding

### ISSUE THREAD

**Issue by dy** [browserify/brfs#92]
There are many cases where having raw data included would be the best solution.

One of such cases is [assemblyscript](https://github.com/AssemblyScript/assemblyscript).
By default, that creates `index.js` entry as:
```js
const fs = require("fs");
const compiled = new WebAssembly.Module(fs.readFileSync(__dirname + "/build/optimized.wasm"));
const imports = {};
Object.defineProperty(module, "exports", {
  get: () => new WebAssembly.Instance(compiled, imports).exports
});
```
That `index.js` is only valid in node.js. It is unclear how we are supposed to include that `wasm` file in browser. The standard solution is async `fetch`, that breaks `sync` fashion of loading modules.
The way [wasmify](https://ghub.io/wasmify) works, as well as the most compact way to define an ArrayBuffer in browser, is using `base64` string with encoded data. Like so
```js
const fs = require("fs");
const b2ab = require('base64-arraybuffer')
const compiled = new WebAssembly.Module(b2ab.decode(fs.readFileSync(__dirname + "/build/optimized.wasm", 'base64')));
const imports = {};
Object.defineProperty(module, "exports", {
  get: () => new WebAssembly.Instance(compiled, imports).exports
});
```
Then we may have brfs to cover such raw data case and use wasm in browser fully synchronously, which is totally fine for small modules.

That would be nice for brfs support raw data, for example with `base64` string method.

Raw brfs would also help with cases like `mp3`/`wav`/`ogg`/etc audio data, `png`/`webp`/`jpg` etc image data.

There is [urify](https://ghub.io/urify) module, but that requires default code to be changed.

Just wonder - what is the main blocker against reading raw buffers as `base64` string and decoding them?

@goto-bus-stop @mattdesl 

Related #67

**Comment by goto-bus-stop** [comment]
It reads a [`Buffer`](https://npmjs.com/package/buffer) instance now like Node.js does, which is important because people might do `.readUInt32LE()` or any Node-specific API on the return value of `readFileSync()`.

Buffers are a subclass of Uint8Array, which has a `.buffer` property, so you can get an ArrayBuffer from it by doing:

```js
fs.readFileSync(__filename).buffer
// → Buffer("bigbase64data/==", "base64").buffer
```

Is that what you're looking for?

**Comment by dy** [comment]
Yes, that’s even better. In general it is not safe to access ‘.buffer’ property, multiple Buffer instances may share single ArrayBuffer, but yes, that’s what I’d expect.

**Comment by Izorth** [comment]
> It reads a [`Buffer`](https://npmjs.com/package/buffer) instance now like Node.js does, which is important because people might do `.readUInt32LE()` or any Node-specific API on the return value of `readFileSync()`.
> 
> Buffers are a subclass of Uint8Array, which has a `.buffer` property, so you can get an ArrayBuffer from it by doing:
> 
> ```js
> fs.readFileSync(__filename).buffer
> // → Buffer("bigbase64data/==", "base64").buffer
> ```
> 
> Is that what you're looking for?

fq damm this is what I was looking for! many thnx dude
